PATCH http://localhost:3000/api/v1/auth/updateUser
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzljZDU5MWU5YTJkZWI2YWUxZDFmMjIiLCJpYXQiOjE2NzEyMjM2NzQsImV4cCI6MTY3MTMxMDA3NH0.4yqxuVEbEnjm_-m899kUIfbovIqZDFfoRBPkdzs2KTE


{
  "email": "person@email",
  "name": "person",
  "lastName": "lastName",
  "location": "my city"
}

###
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "user@email.com",
  "password": "password"
}